--- #YAML:1.0
name:                Tk-WidgetDump
version:             1.35
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Tk:                            800
    Tk::FontDialog:                0
    Tk::HistEntry:                 0.33
    Tk::NumEntry:                  0
    Tk::ObjScanner:                0
    Tk::Pod:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Slaven Rezic (srezic@cpan.org)
